export const countries = [
    { name: 'United States', code: 'US', flag: '🇺🇸', phone: '+1' },
    { name: 'Canada', code: 'CA', flag: '🇨🇦', phone: '+1' },
    { name: 'United Kingdom', code: 'GB', flag: '🇬🇧', phone: '+44' },
    { name: 'Germany', code: 'DE', flag: '🇩🇪', phone: '+49' },
    { name: 'France', code: 'FR', flag: '🇫🇷', phone: '+33' },
    { name: 'Japan', code: 'JP', flag: '🇯🇵', phone: '+81' },
    { name: 'Australia', code: 'AU', flag: '🇦🇺', phone: '+61' },
    { name: 'Brazil', code: 'BR', flag: '🇧🇷', phone: '+55' },
    { name: 'China', code: 'CN', flag: '🇨🇳', phone: '+86' },
    { name: 'India', code: 'IN', flag: '🇮🇳', phone: '+91' },
    { name: 'Russia', code: 'RU', flag: '🇷🇺', phone: '+7' },
    { name: 'South Korea', code: 'KR', flag: '🇰🇷', phone: '+82' },
    { name: 'Mexico', code: 'MX', flag: '🇲🇽', phone: '+52' },
    { name: 'Italy', code: 'IT', flag: '🇮🇹', phone: '+39' },
    { name: 'Spain', code: 'ES', flag: '🇪🇸', phone: '+34' },
    { name: 'Netherlands', code: 'NL', flag: '🇳🇱', phone: '+31' },
    { name: 'Turkey', code: 'TR', flag: '🇹🇷', phone: '+90' },
    { name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦', phone: '+966' },
    { name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪', phone: '+971' },
];
